// CARD ARRAY //
// ********** //

var cardsArr = [
	{
        img: "The Adventurer.jpg",
        youtube: "https://youtu.be/SxlZIXowp3E",
        about: "The Adventurer represents doing new things. Travelling to new places, joining in new activities and doing exciting new things. It represents the need or desire to extend yourself and have new adventures out in the physical world.<br><br>Are you feeling bored with your life or in a rut? Does nothing ever change for you? Are you having the same conversations with the same people about the same topics? Do you long for excitement and adventure and a release from the boring prison of mundane life<br><br>It is easy to forget that human lives are predominately lived in the small bubbles of family, places of work or social groups and you must remind yourself that there is a huge world out there external from you that you can explore.<br><br>When this Servant appears it shows you have a need for something new and wonderful to happen in your life. You have become stuck in a rut and life has become boring and stale. Plan an exciting trip, do something you normally wouldn’t to, or become more spontaneous – adventure awaits! Break out of your well-worn patterns and push yourself out of your comfort zone.<br><br>It can also denote travel, journeys, parties, and exciting occasions.<br><br>You can invoke the help of The Adventurer when you need some excitement or adventure in your life. This is a great Servant to use if you are feeling bored and want something exciting to happen. But you should be careful what they wish for- interesting and exciting times often come with new challenges.<br><br>Banish this Servant if life (or a person) is getting too exciting or too high energy, or is getting out of control – an overload of The Adventurer energy can lead some to become quite mercurial in nature and have an inability to sit still or relax.<br><br>Can also be used to make sure parties and gatherings, holidays or outings are fun, exciting and successful.",
    },
    {
        img: "The Balancer.jpg",
        youtube: "https://youtu.be/suawiMh39-k",
        about: "When this Servant appears she tells you that there is a need for restoring some form of balance in your life.<br><br>Are you spending too much time at work and not enough with your family or having fun? Maybe you are spending too much time on frivolous stuff and not enough time following your passions. Maybe you feel that you have been given too big a share of the workload or responsibilities? Are your finances getting out of control? Are you spending way more than you earn, or even hoarding what you are earning? Now is the time to sort that out before it becomes too late and it wears you down.<br><br>If your life is out of balance in any respect, now is the time to bring harmony to it.<br><br>You can invoke the energy of The Balancer when you need to restore order or balance in your relationships, work-life, or financial matters. Also useful in business matters to keep a healthy balance between expenditure and income.<br><br>The Balancer is very helpful in restoring an equal footing in relationships when you feel someone has gotten the upper hand over you. Asking for The Balancer to even out the playing field can be quite effective.",
    },
    {
        img: "The Carnal.jpg",
        youtube: "https://youtu.be/ITg8FKEF1NM",
        about: "This Servant is all about sexual attraction and pure base animal desires. She can indicate a need to explore or indulge in sexual impulses or desires.<br><br>Do you feel sexy and desirable, or do you feel ugly and unwanted? When The Carnal appears she suggests that now is the time for you to start feeling good about yourself and your physical needs and wants.<br><br>The Carnal reminds us that our sexual needs are important to our well-being and happiness and that we shouldn’t be ashamed of them, or ever try to repress them. The Carnal suggests that you should start to express your sexuality in the manner you have always wanted to. She says you should allow yourself to feel sexy, desired and passionate.<br><br>This Servant is not about love, it is purely about the physical aspects of sex, physicality and desire.<br><br>Invoke the help of The Carnal when you feel the need to feel sexy, passionate and beautiful. She is eager to assist in improving sexual confidence. You should invoke The Carnal to feel the confidence and charisma of this Servant when you are out to impress. You will start to notice people noticing you in a new light.<br><br>You can  ask The Carnal to assist you in becoming a great lover who is desired by all and leaves their lovers wanting more. The Carnal is very useful in aiding the end of a sexual drought or for putting the passion back into a stale relationship. If you are looking for a lusty relationship or a quick fling then The Carnal can help get you what you need.<br><br>The Carnal works best when used for general attraction rather than for a specific person.",
    },
    {
        img: "The Chaste.jpg",
        youtube: "https://youtu.be/UDSrDxvVmq4",
        about: "The Chaste is all about refraining from the base pleasures of life and instead focusing on less physical orientated goals such as virtue, honour, purity and morality. She calls to tell you to concentrate on other areas of your life, not just love, sex or physical desires.<br><br>Although at first glance it may seem like this Servant calls for restriction or a need to stop having fun, but really The Chaste is suggesting that having some discipline or self-control is important to maintaining an overall healthy lifestyle, and becoming a more well-rounded person.<br><br>When this Servant appears she is saying that maybe you should spend less time focusing on your physical wants and desires and instead look inward and start developing other parts of your life – such as friendships, family, self-development or even the overall bigger picture of their life direction and goals. Is there a need to pull back and concentrate on more virtuous matters?<br><br>Perhaps you are spending too much time pursuing sexual gratification and not enough time developing other areas of your life. Has life become all about the next sexual experience? If so, The Chaste suggests now is the time to reevaluate your priorities.<br><br>The Chaste isn’t always a sign for physical abstinence though, she can point to the need to lessen any pursuit that you are focusing on to the detriment of other areas of your life.<br><br>You can invoke the energy of The Chaste if you are trying to pull back from a hedonistic lifestyle and want to move into a more restrained section of your life.<br><br>The Chaste is also helpful in reducing the advances of unwanted amorous admirers, or sexual partners whose sex drive is more than you want or can handle.<br><br>The Chaste can assist in all matters where purity is needed, including purity of mind. If you find yourself attracted to someone that you really shouldn’t be, such as a friend’s partner, then The Chaste can be asked to assist you in to purifying and releasing this harmful attraction.",
    },
    {
        img: "The Conductor.jpg",
        youtube: "https://youtu.be/uDnFEY10fPs",
        about: "The Conductor is the magician of the orchestra, using his wand to control the music and rhythm to his preference.  He is all about taking control and being in charge of the world around you. Are you the conductor leading the orchestra or are you one of the minor players? Are you being swayed in time with the music that’s being played or are you marching to the beat of your own drum?<br><br>This Servant suggests that you take a look at the circumstances of your life and see what roles you are actually playing. Are you just reacting to life and accepting all that comes your way, or are you taking the lead role and living your life the way you want it to be?<br><br>Are you in flow with the music and rhythm of life and the world, or are you out of step with the beat? Is the soundtrack to your life an upbeat triumphant chorus of angels or a lonely solo violin weeping mournfully in the rain?<br><br>The Conductor calls to you  to take more control over your life and to direct the music of this existence to what you want rather than just marching along to the beat of others. While you may never be fully in control of every event that occurs to or around you, you can compose your own life soundtrack to be more individual, beautiful and inspiring.<br><br>The Conductor can help you take control of events, relationships, jobs, circumstances or anything that surrounds you and put your own stamp on it.<br><br>The Conductor can show you how to move and manipulate the events of your life so that they become more harmonious and pleasing to you. The Conductor is a wonderful Servant to enlist when you feel that you don’t have control or autonomy. Request The Conductor to teach you how to weave the music of life to your liking and rhythm.",
    },
    {
        img: "The Contemplator.jpg",
        youtube: "https://youtu.be/CdbOCInRdZA",
        about: "The Contemplator suggests that best course of action is to pull back and withdraw from thinking about your current issue for a period of time. Some problems are best solved by taking a break from thinking about them altogether or sleeping overnight on them. It’s usually when we relax that the solution appears.<br><br>The Contemplator suggests that you turn your concern over to your subconscious mind to solve for you. Let the quandary fall to the back of your mind, and thus allowing the subconscious to find a resolution.<br><br>This Servant can also suggest that something is buried deep within your subconscious mind and that you need to become aware of it. It could be an old idea, a limiting belief, or a bad past experience, but whatever it is, it is tainting your judgement of your current predicament.<br><br>The Contemplator has access to all the information in your subconscious mind. He is aware of all your inner workings, motivations, beliefs and long forgotten memories. He knows the underlying reasons why you do the things you do and don’t do. He knows everything you have done that you weren’t paying attention to. He knows more about you than you do. And you can ask him to supply you with any of this information.<br><br>Any problem can be handed over to The Contemplator for deep processing and a solution found. Visualise yourself psychically handing the issue over to The Contemplator, then try as much as possible to put it out of your mind altogether. Within the next few hours, or maybe days, the solution will suddenly appear fully formed in your mind.<br><br>The Contemplator can be asked to reveal a solution to any problem at hand. Give as full an explanation as possible regarding the nature of the problem and any pertinent information to The Contemplator. This should be spoken out loud.<br><br>In another very humble, but highly effective role, The Contemplator can help you remember details that are temporarily forgotten, such as phone numbers, people’s names, or where you left your keys. Take a brief moment and mentally give the problem to The Contemplator and wait for the reply. It shouldn’t be forced or pressured.<br><br>The Contemplator is also very useful for transferring new skills or information into our long-term subconscious minds for later retrieval or automation. Great for forming new habits or breaking old ones.",
    },
    {
        img: "The Dancer.jpg",
        youtube: "https://youtu.be/mgae2wsOxq4",
        about: "When this Servant appears it is a signal that sometimes the best thing you can do when it rains is to go dance in it. Life can be hard and sometimes things just don’t go the way we wanted them to no matter how hard we try. It is an inevitable part of life that sometimes, despite our finest efforts, we just lose.<br><br>And that’s ok. The Dancer, however, is here to remind you that it’s not ok to just give up.<br><br>The Dancer suggests that rather than spiralling into depression or becoming disheartened that you should rejoice in the effort made, and dance in the rain. Life may be falling apart around you but The Dancer reminds you that you are fully in control of your reactions towards it. You can choose to fall apart or you can choose to laugh along with it.<br><br>The Dancer reminds you that even a failure can be celebrated as it brings with it the lessons that will get you closer to your goals. When life is tough, the Dancer calls out to take things less seriously and just enjoy the moment, no matter what that moment is.<br><br>Ask The Dancer to help you stay afloat when times are tough or when your plans have failed. Invoke The Dancer when you need to pick yourself up and get back into the game.",
    },
    {
        img: "The Dead.jpg",
        youtube: "https://youtu.be/-kUQw7IlFJo",
        about: "This Servant is all about the lessons learned from history – your own personal history and our collective human history. The Dead suggests that you should heed the lessons, warnings, and advice from those who have gone before you. She reminds you that there is a huge amount of wisdom available to you from the experiences of the entire population of the world, including all who have long since died.<br><br>The Dead asks you to reflect on your past experiences so that you don’t make the same mistakes again. For instance, are you making the same mistakes in this relationship as your previous ones? Are you ignoring the experiences of those who have gone before you and think that you know better? Are you dismissing an old fashioned idea or method simply because it is old? Are you ignoring messages and teachings of deceased friends, relatives or people of note?<br><br>The Dead can be used for general ancestor work. An offering to The Dead is an offering to your ancestors and the Mighty Dead and you should thank them for all they have done. Remember, you would not exist if it weren’t for all those who came before you.<br><br>If someone close to you passes, you can ask The Dead to help bring them safely to the other side and to look after them as they make their way into the next stage of their existence.<br><br>You can ask The Dead to carry any messages to the deceased.<br><br>The Dead Servant can also be used to connect to any part of the past,  such as family history, personal history or even the history of the area you live in.<br><br>The Dead is an exceptional Servant to use for emotional healing. If there are parts of your past that need healing you can ask The Dead to assist you to send love or comfort to a time in your life when you needed it most. The Dead can help to reconnect with parts of you that you thought were long gone or even dead.<br><br>Old hatreds or arguments with dead friends or relatives can be appeased or mended by using The Dead Servant as a conduit between the parties.<br><br>The Dead can be asked for general guidance on all matters. She is hugely knowledgeable as she has access to the entire history of human thought and deed.",
    },
    {
        img: "The Depleted.jpg",
        youtube: "https://youtu.be/WrOcjy7HX8E",
        about: "When this Servant appears it usually means that you have run out of energy, money, supplies, or resources and that you should stop and rest before any permanent damage is done. You have put all you can into a particular situation and have become burnt out. All power, energy, and will to continue has been drained from you.<br><br>The Depleted suggests that the only solution is to retreat and restock, regrow and allow the cycles of life to move onto the next, hopefully, more rewarding stage. Winter has come and all growth has ceased. The days are dark and the nights long and no amount of renewed effort can change that.<br><br>Something in your life has run its course and needs to be allowed to end. All things naturally have an endpoint and it can be sometimes hard to let things go, but we must let them go if we are to continue to grow instead of withering away and dying.<br><br>What are you not letting go off? What are you holding on to that has ceased to be of value? Is there a situation that saps all your energy or time that needs to be put to bed for good? Has a relationship gone on so long that now there is nothing of value in it for anyone? Time to let the dying things die, so that new things can grow.<br><br>The Depleted can be used to remove energy from any situation you no longer want to experience.  This, of course, lends itself easily to any sort of curse work- you can instruct The Depleted to drain the energy stores or resources of an enemy.<br><br>While The Depleted can be used to put an end to any situation, relationship or endeavour, it must be noted that in cases of attack magick, the depletion can spread out wider than just the target. Everyone’s life affects the people and events around them, so draining energy from a single person or circumstance will have knock-on effects on the surrounding events and lives. This is unavoidable and as such should always be a consideration.<br><br>The Depleted can be used safely in personal matters to easily end things that have come to their natural conclusion but just refuse to complete cease such as lingering legal matters, or ex’s that just won’t move on.",
    },
    {
        img: "The Desperate.jpg",
        youtube: "https://youtu.be/baw37zDH-1c",
        about: "If you are looking for the most negative Servant, then The Desperate is it. When this Servant appears it is a sign that you are going through an intense period of depression, sadness or hopelessness. Things feel about as bad as they possibly can be and no end seems to be in sight.<br><br>You are feeling frustrated, angry, and hopeless- all at the same time. Nothing matters, no one cares, nothing ever works out, everything is pointless, and only the end of physical life seems like an escape – and even that isn’t a guarantee, as who knows if death is actually any better?<br><br>You have found yourself in a hole that you probably won’t be able to get out of by yourself. This is crisis time and it must be taken seriously for those around them.<br><br>The Desperate suggests that unless you makes big changes in the direction you are headed the future may become, or remain, quite bleak.<br><br>The Desperate is a servant of emotional inner turmoil. Your outward life circumstance may not appear to a causal onlooker to be anything that bad- it might even look good- but inside your head you are in hell, and there is no escape.<br><br>The upside to this is that events can’t get any worse. This is as low and terrible as it gets. Life is cyclical and nothing last forever. When you get to the other side of this initiation you will be all the better for it, and will a much stronger person.<br><br>The function of The Desperate is to be in desperation. This is what he knows, this is all he experiences. You can give him all your desperation, suffering, torment and pain. Give him all your misery, anguish, sorrow and sadness, and let him take it from you and use it to sustain himself. Let The Desperate take on the burden of your hardships, for hardship is all that he knows.<br><br>Love and healing can be sent to The Desperate as an embodiment of all the pain and suffering in the world and throughout history. Offerings made to The Desperate will aid all those enduring suffering and hardship.<br><br>The Desperate can be banished; you can place the sigil on a stone and throw it into the sea, or write the sigil on paper and burn or bury it.<br><br>Like The Depleted Servant, The Desperate also lends itself easily to curse work. Sending The Desperate to torture an enemy is very effective but obviously if things go too far the responsibility will be yours. This is the worst Servant of them all, the most horrible, the most vicious and the most severe. Use only if necessary.",
    },
    {
        img: "The Devil.jpg",
        youtube: "https://youtu.be/n9YKtuPMlO4",
        about: "The Devil Servant knows that something you believe about life or yourself is blocking you from getting what you want. The Devil tells you that you are needlessly restricting yourself because of some rule, or “truth” you have decided to live by or believe.<br><br>When this Servant appears it is a reminder to look at what beliefs, or rules you have around your current situation or problem, and judge whether they are useful or not. The chances are that deep down you don’t really believe these self-imposed rules to be true, but you follow them out of a sense of duty,  or simply because you always just thought that way.<br><br>You have many rules about how you should behave or act, what is acceptable and what isn’t, and even what you are allowed to enjoy and what you shouldn’t enjoy. All your life you have been told that some things are “wrong” or “sinful” but have you ever really stopped to think if you actually agree with these rules?<br><br>The Devil tells you that it is only you making up these rules- there isn’t an ultimate and true morality, just your opinions on the nature of good and evil. The Devil calls for you to let go of guilt and allow yourselves to do and behave the way you feel is right, not what you have may been told is right.<br><br>When you find yourself acting on a restricting belief that you no longer want, visualize The Devil’s sigil pushing this belief away from your body and far away from you.<br><br>If you are unsure of what limiting beliefs you may have that are holding you back, The Devil can be asked to show you them. Events and circumstances will appear in your life such that these beliefs and rules come to the surface for you to observe. Once you recognise them you can begin to work past them and then release them.<br><br>In attack magick, the Devil can be used to bind someone to continue deeper and deeper in their own folly. If you observe that an opponent is doing harm to you, or something you are involved with, due to their personal beliefs and rules, you can send The Devil to push them further into this limiting mindset, bringing it front and centre in their lives. This usually leads to the target fully overcoming their need for these restrictions and seeing their folly. But sometimes they become totally engulfed and further immersed in their belief systems, destroying themselves in the process.",
    },
    {
        img: "The Explorer.jpg",
        youtube: "https://youtu.be/CAChcNiSTKA",
        about: "This Servant is all about self-growth and exploration, personal development, and becoming a better version of who you are. It’s time for you to start breaking out of your personal comfort zones and explore new ideas, passions and talents.<br><br>The Explorer signals a period of learning and self-discovery that while sometimes painful to experience (all growth is somewhat painful as the old must die for the new to live), the end result will always be that you are a much better, happier, confident and more content person.<br><br>The Explorer is the Servant of personal development and self-help. He suggests that you should do a new personal development course, read some self-help books, take up yoga or begin a meditation practice. If you already do these things, then The Explorer tells you to up your game or move into new areas of development.<br><br>The Explorer is a call to realise that you can be much more than you currently are letting yourself be. It’s time to widen yourself, push yourself and see just what you are capable of.<br><br>He also shows up to remind you about skill, talents or goals you may have forgotten about. Have you always wanted to paint, write, start gardening, compose music, or similar but have never gotten round to it? The Explorer suggests that now is the time to start working on developing these skills before they are lost to time forever.<br><br>The Explorer says to set bigger goals, learn new skills, overcome limiting beliefs and go explore more about who you really are. Rekindle or find the brilliance and potential you have within. Strive to become a much better and greater version of yourself.<br><br>The Explorer can be invoked to help with any personal development related tasks or desires. The Explorer can help you discover talents or abilities you aren’t aware you possess.<br><br>He can teach you the skills and knowledge you need to become a stronger and better person<br><br>Invoking The Explorer will show the operator just how big they and their world actually are, and how to make themselves even bigger, wider, more powerful and more complete. The Explorer will help them become the person they are ultimately to become.",
    },
    {
        img: "The Eye.jpg",
        youtube: "https://youtu.be/Z4dggp11lcc",
        about: "When The Eye appears it is a sign that all is going according to plan, even if it doesn’t appear so from your perspective. The catch is that the plan that is on track is the divine plan, which may not be what you had in mind.<br><br>The advice given by this Servant is that even if life appears to be going all wrong or falling apart – it will all work out for the best in the end. You will eventually end up in the place you are meant to be in and when you look back you will see how every moment had to occur exactly as it did to allow everything to fall into place.<br><br>The Eye is also a sign that someone or something from the spirit realm is looking out for you, and that you are being looked after and helped, even if you don’t feel it. Ultimately, The Eye is a reminder of the existence of a higher being or beings watching over us, guiding and helping us from afar.<br><br>The Eye is your connection to the Super Consciousness, of which your own consciousness is just a microcosm or aspect. Invoking The Eye will infuse you with Spirit and Divine presence. This Presence is the original thought that existed at the beginning of all things and will be there at the very end – it is consciousness in the fullest and widest sense. It is all things. It can take many shapes or forms, and will present itself differently to every person.<br><br>The Eye can be used to help you become more in-sync with the higher calling of life. The Eye can be the focus of prayers for the safety, healing and happiness of all sentient beings in the universe.",
    },
    {
        img: "The Father.jpg",
        youtube: "https://youtu.be/vGnmNIeQ9zU",
        about: "When The Father appears it means that someone in your life will offer guidance and wisdom on how to deal with your current issue or problem. However, it may be that you need to seek out such a person if none are at hand.<br><br>This Servant tells you that it is ok to look for help, guidance or to rely on the wisdom of other more experienced people. Someday you may know all the answers but for the time being it is wiser to ask someone who will be able to steer you on the right path.<br><br>The Father loves you, his child, and only wants the best for you, but he knows that sometimes tough love may be the best solution. The Father card tells you that you may be about to hear, or be obliged to do something you don’t like, but that ultimately it is the correct and wise thing to do.<br><br>The Father is full of love and will offer all the wisdom and insight that he has at his disposal. However, he wants you to be able to fend for yourself, with his ultimate goal being that you are able to navigate this world on your own. He believes that the best way for you to learn something is by doing it or experiencing it for yourself.<br><br>Life has hardships and problems that we all must go through, and The Father knows this. He wants you to be prepared for these, and will stand by your side giving advice and wisdom as you do. He won’t protect you from these experiences as he knows the growth and strength that comes from overcoming our own battles and problems. The Father knows that the only true way of learning to not put your hand in the fire is to experience doing it once, no amount of advice can replace experience.<br><br>The Father is an exceptional Servant to use when you need guidance on big life decisions such as: should I switch jobs? Is now a good time to sell? What is the best way to deal with this issue or person?  How do I learn to live without someone? Should I stay in this relationship? Is this a good investment of my time or money? What’s my best next move? The advice may not always be what you want to hear but deep down you will know it is the right move.<br><br>A great Servant for any time when guidance, advice or wisdom is needed on real-life issues.",
    },
    {
        img: "The Fixer.jpg",
        youtube: "https://youtu.be/gGGS43dyxNA",
        about: "Any problem or challenge can be solved, but there is always some cost involved in the solution. The Fixer asks the question:  are you willing to pay the price for what you want? You can get whatever it is that you desire but you will have to accept all the costs that go with it.<br><br>Paying the price, however, doesn’t always mean something terrible. The cost of writing a book, for instance, is the long months or years sitting on your own writing. You must deal with the frustrations and the pain that goes with writing. For some people that pain is totally worth it, for others it really isn’t. The Fixer wants you to think about the costs involved in the resolution of your own situation and asks if you are willing to accept the price.<br><br>Is the resolution of the problem worth the cost or is it better just to walk away?<br><br>The Fixer Servant is only used when all else has failed or no other option is available. He is not a Servant to engage without thinking through fully. Are you willing to do anything to get your desired goal? Are you willing to pay whatever the cost of business is? Many times you may not know the full cost of something until it is over, and by then it is too late to change your mind, so you have to be very sure you are willing to accept whatever fallout occurs.<br><br>To set The Fixer to work, you should explain the circumstances of the problem to him, and then tell him that he should fix it. Then, and most importantly, you should say out loud that you will accept whatever the cost is by stating that you are willing to accept the ramifications of whatever it is that has to be done, or that has to occur in order for you to get your desired outcome. Once on the job he cannot be recalled until the task is complete.<br><br>You’ll know what the price is when you get what you wanted as usually the two things happen at the same time. The Price and The Desire are intrinsically linked. The price you pay is not really to The Fixer, it’s more about what you are OK with happening or doing in order to get what you want.<br><br>As an example: The price of getting a promotion is that the person who currently has the job has to lose it. This could mean they will get fired. It could also mean they too get a promotion. But you can’t know until it happens and you have to be OK with both outcomes.<br><br>The Fixer is only to be used when you have tried every other means. The Fixer will do “whatever it takes” so you have to be sure that’s what you want. Use with extreme caution and only as a last resort.",
    },
    {
        img: "The Fortunate.jpg",
        youtube: "https://youtu.be/HWv3FxdBwe0",
        about: "If The Desperate is the worst Servant to see in a reading then The Fortunate is certainly the best. When The Fortunate appears it is a sign that everything is going really great for you, or is just about to be.<br><br>The Fortunate is a herald of prosperous times- life is good, things are easy, and the future is bright. If this Servant’s card is chosen as an answer to a question, then the answer is a resounding yes!<br><br>The Fortunate tells you that it’s time to live and be happy, to be joyful and relaxed in the knowledge that everything is going perfectly. The sun is shining brightly on you, all the omens are good, and all worries are vanishing. Life is as good as it can be.<br><br>The Fortunate is very effective in all money magick workings. Asking The Fortunate for good luck and good fortune with money is usually very successful. With money magick, it is traditionally suggested that you start with asking for a small amount of money rather than going for billions immediately. While everything is possible, magick works best with the probable – a pay rise is a better ask than a lottery win.<br><br>The Fortunate can also be asked for good luck in any endeavour, including exams, job interviews, opening new businesses, gambling, sports events, and even bargain hunting. You can invoke the energy of The Fortunate at any time you need to feel lucky.<br><br>For curse work you could ask The Fortunate to change the good luck of your enemy into bad luck. Being lucky works both ways, after all.",
    },
    {
        img: "The Gate Keeper.jpg",
        youtube: "https://youtu.be/ZmtL5j_lNqU",
        about: "The Gate Keeper suggests that you feel like you are being locked out of something – a clique, a career path, an opportunity, a family secret, a group or even a physical place such as a new house. It may be just a feeling, or it may be very much the case. You can be locked out because of your own actions, the actions of others, or unavoidable life circumstances. In the reading, other cards may suggest where the fault lies, but perhaps it may already be obvious to you.<br><br>The Gate Keeper says that there is always a way to get access to what we want and it is just a matter of finding the correct procedure, or getting in contact with the right person.<br><br>This Servant can also suggest that information is being deliberately withheld from you. Someone or something is being hidden from view. Someone is keeping something secret.<br><br>The Gate Keeper holds the keys to the other side of the spiritual veil. He can give access to heaven, the underworld, the astral plane, hell, or any other spiritual plane or area that you desire to interact with, in order to communicate with those who dwell there. A spoken request of “Great Servant, The Gate Keeper, please open the door Gate Keeper, so I may pass and speak to those on the other side” with offerings of candles or incense upon your return, is very effective.<br><br>The Gate Keeper can help locate lost or stolen items as no doors are closed to him, and for this reason, he is also exceptional at revealing secrets or hidden things. Nothing can be hidden from The Gate Keeper. The Gate Keeper can grant you access to known places, contacts or opportunities that you are currently locked out of or somehow restricted from entering, such as jobs, new houses, social circles, cliques, or social clubs.",
    },
    {
        img: "The Giver.jpg",
        youtube: "https://youtu.be/7i3hK6N3a2w",
        about: "When The Giver appears it is an indication that a gift is about to be given to you. This gift can take many forms: unexpected money, some good news, generosity from a stranger, a miracle, a heartfelt compliment from a friend, or experiencing something that touches your heart and lifts your soul.<br><br>The Giver is all about generosity and gratitude, and the giving and taking exchange. When this Servant appears in a reading it is a call for you to remember all the gifts that have been given to you, and all the generosity you have experienced in your life. It is easy to forget the goodness in people but this Servant comes to reminds us to be ever grateful for them.<br><br>The Giver is also about miracles and divine gifts – those unexpected occurrences that seem to come from nowhere that change everything, completely remove the problem,  or save us from the depths of despair. Watch out for them, as the appearance of this Servant suggests one is on their way to you.<br><br>The Giver is very useful and powerful to enlist when you are trying to make business deals or are involved in any sort of exchange or trade agreement. The Giver can be asked to ensure that the deal turns out fair for all sides, or at the very least fair for you. The Giver can be used in any working where exchanges are being made.<br><br>The Giver can be engaged to help when you need a minor miracle, but like The Fixer a price must be paid. The price in this case is that you have to return the favour to someone else. Don’t over think this. Sometimes it will be obvious what you must do for someone else in return for your miracle, sometimes it won’t be. Best practice is to just go out of your way to do something nice for another person without wanting or expecting anything in return.<br><br>The Giver can be helpful in cases where you have offered forgiveness but it has not been accepted. At these times ask The Giver to help smoothing things over and restore the relationship.",
    },
    {
        img: "The Guru.jpg",
        youtube: "https://youtu.be/bc4UWp1zMRI",
        about: "The Guru suggests that a new spiritual or magick mentor has entered into your life, or is very shortly about to appear. Guru is a Sanskrit term that connotes someone who is a “teacher, guide, expert, or master” of certain knowledge or field. The Guru can take many forms so don’t be too hasty in dismissing someone because of how they look or behave. Sometimes the best wisdom comes from unexpected quarters.<br><br>The Guru suggests a more one on one relationship than the typical teacher and class system, but doesn’t totally rule it out. The Guru is a teacher, guide, friend, mentor and spiritual counsel. He will impart wisdom, understanding and practical advice rather than just intellectual knowledge. He will show you how to do things rather than why you should do them, or give you the theory behind the practice. The Guru is extremely practical.<br><br>The Guru servant is extremely useful to invoke when you are in need of practical spiritual direction or mentoring in some area of esoterica, magick or spirituality. He is a great Magician and Spiritual Master but his emphasis is always on the practical application of magical or spiritual ideas in your day to day life.<br><br>He is also extremely useful to use when you need to learn any sort of new practical skill. Tell the Guru the problems you are facing, the new skill you want to learn, or the ideas or concepts you are having a challenge implementing in your life, and then ask that they be explained or revealed to you in practical and useful terms.<br><br>The Guru can be invoked during times when you find yourself being asked to give spiritual advice or counsel, but you are not sure what the best advice to give is, or you are being put on the spot and are lost for an answer. Using the sigil, you can invoke The Guru into yourself and allow his wisdom and guidance to pour through you.",
    },
    {
        img: "The Healer.jpg",
        youtube: "https://youtu.be/xgYZ8Z4sLXg",
        about: "The Healer suggest that you may be in danger of getting sick or worn out. This sickness may not be physical; it can be emotional or even spiritual. The appearance of The Healer in a reading suggests that now is the time for you to start looking after yourself. Perhaps you should go get a check up with a doctor or start a healthy eating diet. The Healer also suggest that you should consider exercising more and becoming as physically fit and healthy as possible.<br><br>The Healer can also denote the arrival of a person in your life who will bring with them fantastic healing energy,  or who will be a soothing and healing influence on you and your life. Perhaps it is someone from the past who now wants to settle old hurts, but it could just as easily be someone new to your life who just has a very curative presence.<br><br>If The Healer appears and you are currently sick, then it is a sign that you are on the road to recovery as long as you get the necessary rest and recuperation you need.<br><br>The Healer can be used for all healing work or rituals. This ranges from general “healing the world” offerings to more focused healing sent or aimed at a particular person (or event). Candle offerings work extremely well coupled with asking The Healer to look after your loved ones while they are sick. You can also ask for healing for yourself. Drawing the sigil above sick people (either physically with the hand or just visualising it with the mind) while asking for The Healer’s healing and soothing presence can be beneficial.<br><br>The Healer can also be called to protect and keep safe those who work in the healing, medicine and rescue services.<br><br>NOTE: The Healer is in no way meant as an alternative to your Doctor or conventional medical treatment. If you are sick, get checked out by a professional.",
    },
    {
        img: "The Idea.jpg",
        youtube: "https://youtu.be/p-KLpeE4klg",
        about: "When The Idea appears it is a reminder that you have been given an idea for something that should be expanded upon and brought into existence. These ideas don’t hang around for too long and if you hesitate you may find yourself looking at someone else bringing “your” idea into the world and reaping all the benefits that could have been yours.<br><br>The Idea wanders around looking for people who will take the seed and grow something big out of it. The Idea doesn’t care who the person is who turns the idea into reality, it just wants the creation to get out into the world.<br><br>The Idea urges you that now is the time to develop the ideas you have rather than letting them linger in the back of your mind to work on, or get to “someday” – that someday is now, and if you don’t act soon, someone else will.<br><br>The Idea is great for any situation that needs the creative spark. The Idea is excellent for invoking at the start of a creative project or when some fresh new creative ideas are needed. You can place the sigil in your office or place of work so that a constant flow of ideas and creativity come your way.<br><br>It is also possible to use The Idea to bind an idea to yourself so that no one else uses it. That said, some ideas are so strong that they just need to get out no matter what so it is always better to act soon rather than regret it later.<br><br>Candle offerings to The Idea can help to motivate your team/group/friends to be more creative. Generally, anything to do with creativity, ideas, imagination and inspiration is The Idea’s wheelhouse.",
    },
    {
        img: "The Levitator.jpg",
        youtube: "https://youtu.be/l2PuTcjVHQ4",
        about: "It is easy to take life too seriously or be so rooted in a problem that it is all you can see. The Levitator suggests that you rise above it all and stop participating in the game. Will you care about any of this a month from now? A year from now? Ten years from now? The chances are that the problems that currently feel all-consuming will soon be nothing more than a memory, with their sting or bite long gone.<br><br>The Levitator may also suggest that you should become the bigger person in a problem situation, or argument, and perhaps allow the other person to win for the sake of peace. Maybe you should make the first move towards reconciliation after a falling out or argument with someone.<br><br>When The Levitator appears in a reading it is often a suggestion for you to look at the issues at hand from a different angle. Can you try to see your issue or problem from a different angle or perspective? Try to look at it as if it was happening to someone else. What advice would you give to someone else if they came to you with this problem?<br><br>You can use The Levitator in times when you feel that life is getting to be too much to handle, or if problem after problem is mounting up and you feel like you have no escape. The Levitator can show you the situation from a higher or wider perspective, where a bigger, more complete picture is clearly seen. From this point of view you may get a better insight into the solution of your problem or at the very least the reason why you must endure it.<br><br>If there is a need for you to be the “bigger person” in a situation, advice can be sought from The Levitator on what is the best approach to take.<br><br>If your life has become too much about other people’s drama, or a situation has become toxic, invoke The Levitator to rise above it all and become unaffected by all that is occurring. Also useful when you need to take the moral high ground.<br><br>The Levitator can also be used if you are pursuing the development of the spiritual siddhis. Invoking is key to this.",
    },
    {
        img: "The Librarian.jpg",
        youtube: "https://youtu.be/nb1_lsejQco",
        about: "The Librarian is all about studying, researching and gathering information. It is about the theory and information rather than practical application. The Librarian is interested in knowing rather than doing. She can often be a sign that education and learning of some form is important to you or that it is about to play a big part in your life.<br><br>The Librarian is mostly connected to formal education, but self-learning, rather than being taught by a teacher, is not to be ruled out as a possibility. When The Librarian appears there is often a sense of the need to gain further knowledge on a subject or problem. It may be a sign that you need to research more about the problem or topic at hand, or someway get your nose into the books. Might also indicate a return to education or doing course work.<br><br>The Librarian is a great Servant to use if you are having difficulty in procuring a particular book. A candle offering made to The Librarian with the name of the book to be located written on paper underneath it, has usually terrific results. Audiobooks, PDFs, comics or any sort of media can also be asked for.<br><br>Equally, if you are looking for a certain piece of information or data, then The Librarian is a great Servant to help with tracking it down. You can ask for what you need and will subsequently have the information come to you synchronisticaly.<br><br>The Librarian is also very useful if you are studying or taking exams or doing a test. A series of candle offerings, or even a novena, is very effective around exam time. Her sigil can be placed in the study area so that you retain more of the information you read. The sigil placed in the exam hall, if possible, can also be hugely beneficial.",
    },
    {
        img: "The Lovers.jpg",
        youtube: "https://youtu.be/yiMLdChD56o",
        about: "The Lovers is not about sex or lust – it is about intimacy and acceptance. It’s about partnerships, trust and synergy. It’s about two separate people or things joining as one. It is about union.<br><br>The Lovers recalls that moment after your lust has been satisfied and you still want the other person to be close to you. It’s the relationship after the honeymoon period where the couple really fall in love as people rather than as physical lovers. The Lovers reminds you about the closeness and union that bonds great relationships.<br><br>When The Lovers appears in a reading it suggests that there is a need for partnership. The Lovers often signals business partnerships, or new significant friendships, but it also represents deepening romantic relationships.<br><br>The Lovers can be used when you are looking for a lasting relationship, it is not a Servant for those looking for quick and easy love hook-ups with no strings attached (The Carnal is a more suitable Servant for that sort of working). Instead The Lovers is used to attract a life mate or long-term relationship.<br><br>The Lovers is also great when trying to make a relationship more loving, warm or generally closer. Candles, rose incenses, or indeed roses themselves make great offerings to The Lovers.<br><br>The Lovers is very helpful when you want to move a casual relationship to the next level, or when significant changes need to be made to the dynamic of a current relationship without causing long-term or irrevocable damage.",
    },
    {
        img: "The Master.jpg",
        youtube: "https://youtu.be/hehNJjo0WyE",
        about: "The Master asks: what would you do if you were the best version of yourself? How would you approach the situation at hand from the point of view of an enlightened being?<br><br>The Master is you on your very best day – it’s you on the day when you are able to handle everything the world throws at you – and with style. The Master knows in every moment what the best approach is, what to say and how to react because he has seen all this before and knows how to deal with it quickly, easily and expertly.<br><br>If you were the person you want to be what would you do, say, or think? How would you behave? This mindset can be used in times when there is a need for extra strength or confidence.<br><br>You should think of the person you were five, or ten, or twenty years ago and realise how much more you know about life now than you did then. Then think about how much you would know if you lived to be a thousand years old, a million years old or until the end of all time. How would this version of you (the ideal, or master version) deal with your current situations, goals, worries or relationships? What would the perfected version of you do?<br><br>The Master is the connection to your Holy Guardian Angel / Daemon / Perfected Self/ Higher Self / Ascended Master/ Watcher or whatever name you choose to call it. You can use the image of the Servant as a gateway to communication with the HGA. Offerings and prayer work very effectively, as does carrying the sigil on your person or using it as a focus in concentration exercises.<br><br>Meditation upon the image of the card, or sigil, along with the intention to make contact with your Higher Being can be highly effective.<br><br>A great way to allow the energy of The Master into your life is to surrender to him and allow him to instruct and guide you on the right path. Remember The Master is you, so you are not bowing down or worshipping an external divine being, you are simply acknowledging your own divinity in its most complete and perfected form.",
    },
    {
        img: "The Media.jpg",
        youtube: "https://youtu.be/qwO9B6PEuMc",
        about: "When The Media appears it is a warning that everything is not as it seems. You are being fed a story that isn’t the full truth, or has been spun to make one side look more favorable than the other.<br><br>The story that is being presented has been designed to create a certain reaction or response. This version of the truth may be presented in order to fool you or it may be that someone is trying to spare your feelings about something. Either way, the whole truth is not being told. Things are probably not as they seem, there is a level of spin, lies, manipulation and fraud. The story isn’t an outright lie or falsehood however, some elements are in fact the truth. It has just been presented in a way that distorts the full truth of the situation.<br><br>The Media may also suggest that you are being influenced by outside forces to think or believe a certain way, and it is up to you to try to work out the real truth of the situation. The world around you may not be exactly as you think. The Media calls for you to make your own judgments about events and not rely so heavily on other people’s opinions and life views.<br><br>In a reading The Media can sometimes suggest that someone is slandering or spreading gossip or lies about you. Also very much a reminder that you shouldn’t believe everything you hear, read or see on the internet, newspapers, or on TV.<br><br>The Media represents propaganda and half-truths, whereas The Moon would suggests outright lies and falsehoods. The Media can be used to help see the truth of a situation, to distinguish the spin from the truth or to get a better feel, or read, of a situation or event.  The Media is also useful in propaganda and self-promotion, to help gain publicity or in “getting the word out”.  The Media can be extremely useful in getting a good image of you or your product presented to the world. It can also help restore your good name after a period of it being tarnished. Highly effective in generating a buzz around a new project or product, and generally making the public see you in a good light.<br><br>In curse work The Media is a very useful aid to destroy the good name, or public reputation of an enemy.",
    },
    {
        img: "The Messenger.jpg",
        youtube: "https://youtu.be/SnZpltAWAFk",
        about: "The Messenger is a sign that someone, or something, is trying to communicate with you and that perhaps you aren’t giving the message your full attention. Sometimes we can be so wrapped up in an event that we just can’t see the good news in front of us. However, this Servant can also be a sign that you aren’t facing up to some truth that you’d prefer to ignore, or you are refusing to see someone else’s point of view on a topic. Is there something that people aren’t allowed to speak about to you? Are there topics that you refuse to talk about? Are there areas of your life that you won’t discuss with others?<br><br>The Messenger is a general indicator for you to listen, and become more open to the communication going on around you. Try to make sure that you are heeding, receiving and being receptive to all messages that are coming your way. Someone is trying to tell you something, but are you listening?<br><br>The Messenger is useful for any magick work that involves communications, such as sending or receiving emails, giving talks or presentations, any sort of public speaking, writing blogs, or any sort of journalism. Also helpful when trying to get through to someone on a particular topic or idea.  This Servant can be used to get people talking again after arguments, or when communication between two parties breaks down.<br><br>The Messenger is also effective in finding a channel to get a message to someone whom you have been long out of touch with and are not sure how to contact again. It is even useful when the other person is refusing to communicate with you. To ask The Messenger to deliver a message, simply write it down on a piece of paper, fold it over and put the person’s name on it. Then make a candle offering to The Messenger in front of its image or sigil. When the candle has burned down nearly completely use the flame to burn the paper with your message written on it. Then blow or throw the remaining ash into the wind.",
    },
    {
        img: "The Monk.jpg",
        youtube: "https://youtu.be/X1B_ZG18olA",
        about: "When the Monk appears in a reading it can be a sign that you are overloading your life with too much “stuff” and the best course of action would be to simplify, and uncomplicate your life a bit.<br><br>The Monk calls for silence, calm, relaxation and time spent away from the rat race. The Monk suggests that you spend time in simplicity, perhaps meditating, doing some introspection or contemplative exercises designed to slow you down and focus on the now. Turn off the outer world for a while and come back to the simple inner world.<br><br>The Monk suggests that a period of quiet and calm may be the best medicine for what ails you. Quiet time without TVs, mobile devices or the internet may be called for, along with some long walks out alone in nature, or doing simple things that you enjoy doing just for enjoyment’s sake – not to learn, not to better yourself, not to get ahead – just to for the delight of the act itself..<br><br>The Monk asks you “do you need all the ‘stuff” that you have surrounded yourself with or could you let go of some of it?”<br><br>The Monk can be used any time you want to enter into a period of peace, calm or simplicity. A very favorable Servant to keep an image of in your meditation area. A quick prayer or offering before your meditation practice can also be extremely beneficial.<br><br>If life is getting a bit too much or complicated for you – if you find yourself surrounded by too much stuff or drama then an invocation of The Monk can be very beneficial in starting to make your life more simple and quiet.<br><br>Utilising The Monk in banishing rituals to rid the operator’s life of needless baggage can be extremely beneficial.",
    },
    {
        img: "The Moon.jpg",
        youtube: "https://youtu.be/RuzktwY-YY8",
        about: "The Moon is about hope. In the darkness of the black night The Moon will shower us with her gentle illumination. The Moon is the light at the end of the tunnel. But a word of caution: Hope can set you up for a big fall. Hope is a dangerous thing, after all. That said, hope is sometimes the only thing that can get you through the darker times of your life, and it has to be said that sometimes we get more than we ever hoped for.<br><br>The Moon often represents your ‘shadow’ self – the bits of you that you don’t want to acknowledge. You should aim to become aware of any tendencies you may have to project fear and anxiety onto the events or people that surround you. Then try to turn this negative energy into a positive and constructive energy. Life reflects back to you your thoughts and beliefs in the same way the moon reflects the sun’s light. Remember The Moon has no light of its own, it’s merely reflecting the sun’s light.<br><br>The Moon is a mystery and can represent a number of things depending on the question asked or the problem at hand. As The Moon has no light of its own, it can represent illusion or falseness in some aspect of the your life – is someone you know pretending to be something they are not, or are you pretending to be someone or something you aren’t? This is made more likely if The Media card also appears in a reading. While The Media represents propaganda and half-truths, The Moon mostly suggests outright lies and falsehoods.<br><br>The Moon is an extremely useful Servant for seeing past the illusions of daily life, the lies people tell and of course the lies we tell ourselves. The Moon can shed light on our self-deceptions, like a beam of light shining in a darkened room. The Moon can be invoked to enable you to see what you are hiding from yourself or what falsehood your shadow self is insisting is true. You will be able to see the repressed and unknown sides of your personality that are holding you back. This can be extremely hard and tortuous work but also probably the most rewarding in terms of genuine clarity and increased happiness in life.<br><br>The Moon can help you to look past the story and lies, and see the truth. The Moon’s sigil can be used during conversations or interactions to aid in seeing if someone is being deceitful or lying. Mentally push the sigil into the persons head as they talk and see if they trip up or give in and tell the truth.<br><br>The Moon works extremely well when used on the night of the full moon, as one would expect.",
    },
    {
        img: "The Mother.jpg",
        youtube: "https://youtu.be/QtltfqN-ZHc",
        about: "The Mother comes to show you that life is offering you affection, support, nurturing and unconditional love. You are reminded that you are allowed to be whatever or whoever you want to be and all you have to do is move ever closer towards your goals.<br><br>The Mother brings a huge hug from the universe, full of acceptance, love and affection. Everything right now is ok. You can relax and feel safe in the sweet embrace of the ever loving Mother.<br><br>This Servant shows a need to be loved and looked after by life. You may be feeling the desire to be nurtured by life, and the appearance of this card suggests that this is a reality.<br><br>The Mother always heralds the birth of new things rather than the end of old things. She can be a sign of pregnancy, or the beginning of a new period in your life such as new job, new relationships or new home. The Mother represent fertility in all its different aspects. She is the embodiment of the earth elemental energy.<br><br>The Mother is to be invoked when you need to feel loved by life and you need to feel the unconditional love that is emanating from The Mother’s heart.<br><br>The Mother is very useful for people wishing to conceive or start a family. Candle offerings, prayers or novenas are suggested. The Mother is also extremely helpful in all magick concerning children and family. The Mother can be enlisted to keep children safe and out of trouble, and to make sure they feel loved and appreciated. The Mother can be invoked to aid in becoming a better parent or guardian.<br><br>The Mother is useful in all types of fertility magick including money magick. As a representation of the earth element, The Mother can be invoked to help with stability, growth and strength.",
    },
    {
        img: "The Opposer.jpg",
        youtube: "https://youtu.be/y2hm-cBQjPM",
        about: "When The Opposer appears it is an indication that you are being restricted by outside forces or influences. Someone or something is stopping you from getting your way – this could be laws, social customs, family obligations or traditions or social pressure, but often represents an actual person in your life.<br><br>Although they both deal with restriction or limiting, The Devil points at restrictions from within yourself, while The Opposer is about restrictions coming from outside forces.<br><br>You can overcome this resistance but the victory can only be achieved by action- it will not resolve itself if ignored. There must be some form of a battle with the opposing force for the oppression to cease. The Opposer will never back down unless confronted and even then events may get worse before a solution is found. This may result in the need for you to walk away – but not always; this isn’t a card of failure or defeat. It’s just a sign that a battle is ahead and you must prepare yourself for that.<br><br>The Opposer reminds you that for the most part these restrictions aren’t actually real in an absolute sense, but going against them will usually come with a penalty or punishment. For instance, you can drive your car at any speed you desire, but if you get caught going too fast in a restricted area you will have to face the consequences and pay the fine. <br><br>The Opposer can be banished when someone appears in your life that is getting in your way, messing with your plans, or is placing some sort of restrictions on you.  Drawing The Opposer’s sigil along with writing your target person’s name on a stone and then throwing it into the sea or a river is a great banishing. As is writing the person’s name along with The Opposer’s sigil on paper and then burning it.<br><br>In baneful magick, The Opposer can be sent to restrict an enemy in their plans. Also useful when trying to stop new laws being created, or to stop decisions being made. Also useful for restricting planning permission or permits.",
    },
    {
        img: "The Planet.jpg",
        youtube: "https://youtu.be/tbbP2pe4mjo",
        about: "The Planet suggests that you try to view life in the cosmic sense for a moment and try to see the huge tapestry and wonder of creation. The Planet asks you to ponder what it is all about.<br><br>The Planet moves ‘round the universe in a precise orbit and trajectory. It reminds you of the patterns of life and the different seasons that they must go through. The universe is a vast and ancient place and has experienced more than humans could possibly imagine. You must remember that you are as much a part of creation as the planets, the solar systems, the suns, and the galaxies. You are a child of the stars and you should try to remember that when life seems not worth living or worth the effort.<br><br>However, if you are starting to take yourself too seriously or feeling that you are of immense importance to the universe, or humanity as a whole, then The Planet arrives to remind you that your life, while part of the great whole, is just a tiny, tiny fraction of it and no matter what you do or achieve it doesn’t really compare to anything on the grand scale of things. The Planet reminds you to be aware of your individual insignificance and to stop claiming to be more than they actually are.<br><br>The Planet wants you to be aware of what you have captured in your own atmosphere and gravitational pull. Is everything in your personal orbit helpful and useful, or have you surrounded yourself with junk or negativity? Extra note should be taken of this idea if The Planet appears with The Monk.<br><br>The Planet is an extremely useful Servant in rituals where you need to feel extremely big and powerful or where massive results are needed. The Planet is the Servant of manifesting as The Planet’s gravity can pull to it anything that is needed. But always keep in mind just how easy it is to clutter up the atmosphere with useless stuff.<br><br>The Planet can be used in banishing rituals to clear your orbit of useless debris and junk that you have accumulated over the years. Very useful in all banishing type rituals.<br><br>The Planet can also be used to see the patterns and seasons of life. Invoke The Planet to see the orbits and patterns that the operator is spinning around in. If you find that you are just repeating patterns over and over again, use The Planet to break the cycle.",
    },
    {
        img: "The Protector.jpg",
        youtube: "https://youtu.be/7xLUY5GHyeY",
        about: "When The Protector appears it is a sign that protection and security is, or should be a concern for you. While it’s not a call to become overly paranoid about security issues, The Protector does suggest that you should make an effort to keep yourself out of harm’s way, or to refrain from making any foolish moves that could land you in trouble.<br><br>The Protector can also be a sign that someone is looking out for you or protecting you from behind the scenes. The Protector can easily denote a guardian person such as a parent, partner or law officer.In a divination, the true implications of this card, more than a lot of the others, will be best known by the cards appearing around it or by the question asked.<br><br>The Protector is the go-to servant for any time you feel you are in danger or your safety has been compromised. The sigil can be drawn in the mind’s eye, or in the air in front of you, as a real time strategy during occasions when you feel the need for extra protection.<br><br>The Protector can also be sent to events and occasions in the future (such as vacation time, for safe travel), or to protect particular items. Keeping the sigil on your person at all times will aid in on-going protection. Placing the sigil over the main door to serve as protection for the household is equally helpful.<br><br>Candle offerings to The Protector are helpful in returning curses or magical attacks back to the sender.",
    },
    {
        img: "The Protester.jpg",
        youtube: "https://youtu.be/ZWAO45afXNM",
        about: "The Protester appears when you feel that your concerns aren’t being listened to. You feel an injustice and no longer want to stand idly by and let it happen. The Protester embodies directed anger and frustration against that which you are facing. This Servant calls to you to do more than just be angry or outraged at events – it suggests that you should use this powerful energy to effect change.<br><br>This Servant can also appear when you feel a great injustice has occurred or that you are being oppressed or restricted. If this Servant appears together with The Opposer, The Media, The Moon, The Devil or similar Servants then it is a sign that you have to start standing up for yourself or else you will be crushed and unheard.<br><br>This Servant appears when things have become unacceptable and the time has come for action and change. It can suggest an argument or disagreement is in store or some sort of injustice is likely to occur that is likely to enrage or upset you.<br><br>The Protester is a Servant encompassing the energy of Mars, the God of War. This Servant is extremely useful if you need to go into battle or win a fight. Invoking The Protester is extremely useful during business negotiations, circumstances that require a strong hand, or before actual physical fights. Also very useful in sports and games.<br><br>The Protester is also extremely useful in turning anger and rage into a powerful force of change rather than into frustration.  The sigil can be used to channel angry energy into healthier outlets such as exercise, increasing ambition, goal setting, or self-determination.<br><br>In baneful work The Protester can be made to aid in encouraging dissent in fellow work mates, friends or the general public, or to enlist them to your cause.",
    },
    {
        img: "The Road Opener.jpg",
        youtube: "https://youtu.be/xogeXB_mivw",
        about: "When The Road Opener appears it is a sign that the future is going to lead to new and interesting places. New opportunities are now becoming available, and an improvement in job, love or financial prospects is literally on the horizon.<br><br>The Road Opener is a sign that the way ahead is clear and that you should pursue your goals with all your might as nothing can now stop you from achieving what you want.<br><br>The Road Opener can also be a sign that an obstacle that was once in your way has now been removed (or in the case of a future card – will be) and you are now better fixed to move forward. The Road Opener is always a positive sign of better things to come.<br><br>The Road Opener can be used to open new paths or for clearing obstacles from existing paths. These paths can be career, relationship, creative, or any area that you want to become freer to pursue. You can ask The Road Opener to create new opportunities for you or to show you avenues of interest that you might not have previously considered but which would suit you well and bring you great enjoyment. Candle offerings are very useful, as is drawing the sigils in the air and breathing or pushing it into job applications, or CVs or résumés.<br><br>If someone or something is standing in your way The Road Opener can be enlisted to help in the removal of this obstacle. A form or aspect of the great god Ganesha appears above the open road and He is known as the great remover of obstacles. Chanting “Aum Gam Ganapataye Namaha” over the Servant’s image while seeing your block or obstacle dissolve can be extremely effective.<br><br>A general road opening working could be done to open any suitable paths, which can lead to some unexpected but amazing new directions.",
    },
    {
        img: "The Saint.jpg ",
        youtube: "https://youtu.be/dbjrRSvYTGM",
        about: "When The Saint appears it is a sign that you might be best served by asking someone to intercede on your behalf rather than going directly yourself. For instance, you may benefit from someone putting a good word in with a prospective boss before applying for the job or making contact yourself.<br><br>If an argument has occurred between you and someone else, The Saint suggests that the best course of action is to ask a mutual third party to help smooth things over with the other person first before you talk to them yourself.<br><br>The Saint also suggests that it is often better to use an expert than try to do something yourself. Using an expert may be more expensive in the short term but will save you a lot more in the long term. The best person for the job at hand is someone who knows exactly what they are doing and have experience in dealing with similar cases. Now is not the time to try to learn a new skill.<br><br>The Saint is the patron of magick and can lend his power to you when tasks that would be normally out of your ability range need to be performed.<br><br>If a person, a spirit, a demon or similar has not answered your call or requests for assistance, you can ask The Saint to help make contact and put in a good word for you. The Saint is often used as the first Servant who then introduces you to the rest of the Servants.<br><br>The Saint can intercede for you in presenting your goals, prayers, wishes, healing requests, or any other needs to the higher powers. If you feel that your prayers aren’t being heard, or your magick isn’t as effective as it should be, then an offering in front of The Saint’s image is suggested to ask him to help you get the powers that be listening to you.<br><br>The Saint can also intercede with other people – if you need someone to warm to you, you can send The Saint in advance to help make the target more receptive and welcoming.",
    },
    {
        img: "The Seer.jpg",
        youtube: "https://youtu.be/fu6Ps1IStSs",
        about: "When The Seer appears it is a sign for you to trust your gut and follow your instinct rather than try to work out the problem at hand using analytical methods. You should feel rather than think your way to the solution.<br><br>If a big decision is to be made, The Seer suggests that you should go with what feels best rather than what may be logically best. A job with less money and fewer future prospects might be a better fit for you long-term than a high paid job with prospects for advancement, for instance. You know in your heart what the right decision is and it is often the opposite of what appears to be the best decision. If you have to make a choice between two directions in life and you want to really know what your gut decision is then just toss a coin in the air to decide. However, while the coin is in the air take notice of which side you want the coin to land on. That is the direction you actually want to go in and The Seer is telling you to follow it. The actual side the coin lands on is irrelevant.<br><br>The Seer suggests that you should feel your way through life for a while rather than trying to mentally work out the best move available or rigidly planning.<br><br>The Seer is also about going with the flow and seeing what happens. Letting life lead you for a time, rather than pushing against it and trying to mold it into your vision. The Seer suggests that you sit back from the driving seat and see where the natural currents and tides of your life bring you.<br><br>The Seer can be used to increase your intuition, sensitivities, or emotional guidance system. Invoking The Seer can aid you in becoming more in touch with the energies around you, and give you a better feel of the surrounding events/people/problems from an intuitive level rather than an intellectual one.<br><br>The Seer is a wonderful Servant to use when you feel you are over-thinking decisions or problems. Candle offerings in return for help with getting in touch with the inner-knowing power can be extremely beneficial.<br><br>Invoke The Seer during any time that you need to feel rather than think your way through something.",
    },
    {
        img: "The Sun.jpg",
        youtube: "https://youtu.be/a5JCUM9FSOY",
        about: "The Sun is all about power and energy. When it appears it is a sign that you are in or about to enter a period of high power, vitality, and success. The Sun suggests radiance, abundance, strength, luck, wellness, health, enthusiasm, success and enlightenment. It is a great Servant to see as it always heralds excellent times.<br><br>All power on this planet comes from The Sun, the same for growth and light. The Sun Servant tells you that you have a huge source of power available to you and now is the time to start utilising it.<br><br>The Sun Servant can be used to increase your spiritual or physical energy, for personal growth and for the increase of light in all areas of their life. Invoking The Sun Servant when weakness is felt or extra power is needed is extremely effective.<br><br>The Sun Servant can also be used to illuminate areas or events that are occulted to you. Petition The Sun to show that which is hidden in the darkness, or for illumination on a topic which eludes you. The Sun is helpful to invoke during exercise, weight-lifting and sporting events to draw power directly from the source.<br><br>The Sun can be used to boost the power and effectiveness of other Servants or any magickal ritual. It can add power, potency, and energy to any endeavor, ritual, person, idea or event.<br><br>A very powerful servant.",
    },
    {
        img: "The Thinker.jpg",
        youtube: "https://youtu.be/hQpe1kMRLbk",
        about: "The problem you face will be best solved using reason and deduction. The Thinker is a sign that you need to put aside any emotional feelings or needs you have for the time being, and instead try to focus on the rational and intellectual thoughts instead.<br><br>There is a time to feel your way through life and there is a time to really think things through, and The Thinker instructs you that now is a time to think rather than intuit.  What is the most rational way out of the problem? What will be best long-term even if it feels bad in the short-term? What is the clever move here? What is the most intelligent next step?<br><br>The Thinker wants you to think everything through rather than act on impulse or emotion.  The right solution may not be the answer you want to hear but it is the most logical, and the one that should bring you the best long-term results. The Thinker requires you not to be fooled by your emotions but instead to really think about what is the wisest path to take.<br><br>The Thinker Servant can be used for problem solving using logic or when a decision needs to be made but the process is being clouded by your emotions. The Thinker can help you realise what the best and most astute way forward is.<br><br>You can invoke The Thinker in times when emotions are running high and a calm logical mind is needed. The sigil placed in the air in front of you, either mentally or physically, can aid in cutting down the high emotions of a situation or event and allow you to see what is in front of you rationally and intellectually.",
    },
    {
        img: "The Witch.jpg",
        youtube: "https://youtu.be/fqgELN1oj8E",
        about: "When The Witch appears in a reading it is a sign that there is a touch of magick in the air. The Witch tells you to become aware of the sense that something wyrd is at play that seems to have a life and volition of its own. Something special is happening or about to happen to you- something that may seem strange and unusual at first but will leave you with a sense of wonder. People, events or things may appear suddenly in your life as if by magick, or you will find yourself perfectly in the right place at the right time. Events will magically fall into place and good luck will abound.The Witch leaves you with a sense of wonder, just like a knowing smile or wink from the universe. Magick is at play, and it is a joy to behold, so make sure you watch out for it.<br><br>In extreme circumstances The Witch can be a sign that something malevolent is working against you. Look to the other cards in the reading for clarification.<br><br>The Witch Servant is useful in almost any situation. Any magick, ritual or working can be increased in potency by including or invoking The Witch. She is by a long stretch the factotum of the Servants. The Witch can also teach you magick. Candle offerings as a thanks is suggested when asking The Witch for knowledge or help. She is also a fan of rum, tobacco, herbs, oils and spices and these can be used as an offering for any work she completes for you.<br><br>The Witch sigil can be used in real time to add magick to any event, person or problem – most effectively done by drawing it in the air with the first finger of the left hand or with a wand. The sigil is very useful for enchanting items, banishing energy (visualise the sigil in front and around you blocking any negative energy from getting to you) and in general protection magick.<br><br>Invoke The Witch to feel the magick of the surrounding area, increase potency or to get in the correct frame for ritual. The Witch is the most versatile of all the Servants and is extremely proficient in all areas. If you are ever unsure of what Servant would be the best for your particular issue you won’t go far wrong by enlisting The Witch’s help.",
    }
];


// SHUFFLE //
// ******* //

//Selector for Card Boxes
var cards = document.getElementsByClassName("spread-box");
var original = document.querySelectorAll(".img-all");

// Start Shuffle Animation
function shufflesOn() {
    Array.prototype.forEach.call(cards, function (element) {
        element.classList.add("shuffles")
    })
    Array.prototype.forEach.call(original, function (element) {
        element.src = "./The Forty Servants Digital Deck/Cardback.jpg"
    })
}


// Actual Shuffle & End of Shuffle Animation
function shufflesOff() {
    var x = cardsArr.slice();
    
    var randomCard1 = x.splice(Math.floor(Math.random()*x.length),1)[0];
    var randomCard2 = x.splice(Math.floor(Math.random()*x.length),1)[0];
    var randomCard3 = x.splice(Math.floor(Math.random()*x.length),1)[0];
    var randomCard4 = x.splice(Math.floor(Math.random()*x.length),1)[0];
    var randomCard5 = x.splice(Math.floor(Math.random()*x.length),1)[0];

    document.getElementById("img1").src = "./The Forty Servants Digital Deck/" + randomCard1.img;
    document.getElementById("link1").href = randomCard1.youtube;
    document.getElementById("tip-info1").innerHTML = randomCard1.about;
    
    document.getElementById("img2").src = "./The Forty Servants Digital Deck/" + randomCard2.img;
    document.getElementById("link2").href = randomCard2.youtube;
    document.getElementById("tip-info2").innerHTML = randomCard2.about;
    
    document.getElementById("img3").src = "./The Forty Servants Digital Deck/" + randomCard3.img;
    document.getElementById("link3").href = randomCard3.youtube;
    document.getElementById("tip-info3").innerHTML = randomCard3.about;

    document.getElementById("img4").src = "./The Forty Servants Digital Deck/" + randomCard4.img;
    document.getElementById("link4").href = randomCard4.youtube;
    document.getElementById("tip-info4").innerHTML = randomCard4.about;

    document.getElementById("img5").src = "./The Forty Servants Digital Deck/" + randomCard5.img;
    document.getElementById("link5").href = randomCard5.youtube;
    document.getElementById("tip-info5").innerHTML = randomCard5.about;
    
    Array.prototype.forEach.call(cards, function (element) {
        element.classList.remove("shuffles");
    });
}

//Avoids Extra Shuffle On Mouseout
function shufflesOff2() {
    var cards = document.getElementsByClassName("spread-box");
    Array.prototype.forEach.call(cards, function (element) {
        element.classList.remove("shuffles");
    });  
}

// Allows for Spacebar to be used as Shuffle
document.addEventListener("keydown", checkDown);
document.addEventListener("keyup", checkUp);

function checkDown(e) {
    var key = e.which || e.keyCode;
    if (key === 32) shufflesOn();
}

function checkUp(e) {
    var key = e.which || e.keyCode;
    if (key === 32) shufflesOff();
}


// HIDE & SHOW //
// *********** //

var lis = document.querySelectorAll("li");
var spread1 = document.getElementById("spread1");
var spread2 = document.getElementById("spread2");
var spread3 = document.getElementById("spread3");
var spread4 = document.getElementById("spread4");
var spread5 = document.getElementById("spread5");

for(var i = 0; i<lis.length; i++){
    lis[0].addEventListener("click", function(){
        spread1.classList.toggle("hide");
        this.children[0].classList.toggle("menuglow");
});
}

for(var i = 0; i<lis.length; i++){
    lis[1].addEventListener("click", function(){
        spread2.classList.toggle("hide");
        this.children[0].classList.toggle("menuglow");
    });
}

for(var i = 0; i<lis.length; i++){
    lis[2].addEventListener("click", function(){
        spread3.classList.toggle("hide");
        this.children[0].classList.toggle("menuglow");
    });
}

for(var i = 0; i<lis.length; i++){
    lis[3].addEventListener("click", function(){
        spread4.classList.toggle("hide");
        this.children[0].classList.toggle("menuglow");
    });
}

for(var i = 0; i<lis.length; i++){
    lis[4].addEventListener("click", function(){
        spread5.classList.toggle("hide");
        this.children[0].classList.toggle("menuglow");
    });
}


// TOOLTIP //
// ******* //